name: test-simple

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"

  pull_request: ~

  workflow_dispatch: ~

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build & Test
        run: whoami

      - name: Notify Teams
        if: always()
        uses: ./
        with:
          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
          notify_on: |
            success
