name: test-complex

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"

  pull_request: ~

  workflow_dispatch: ~

jobs:
  qa:
    name: qa
    runs-on: ubuntu-latest
    steps:
      - name: Code QA
        run: whoami

  ci:
    name: ci
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Build & Test
        run: whoami

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy
        run: whoami

  notify:
    name: notify
    runs-on: ubuntu-latest
    needs:
      - qa
      - ci
      - deploy
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Notify Teams
        uses: ./
        with:
          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
          needs_context: ${{ toJSON(needs) }}
          notify_on: |
            success
